name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk@v0.2.3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: ./snake.svg

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update snake.svg"
          git push origin HEAD:output

